FROM osrf/ros:noetic-desktop-full

RUN apt-get update

# Some basic utilities
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y \
    gnupg2 curl lsb-core vim wget python3-pip libpng16-16 libjpeg-turbo8 libtiff5 \
    tmux ranger magic htop build-essential git cmake unzip pkg-config autoconf \
    python3-dev \
    # ROS dependencies
    python3-catkin-tools python3-osrf-pycommon \
    ros-noetic-cv-bridge ros-noetic-image-transport ros-noetic-tf ros-noetic-message-filters \
    ros-noetic-hector-trajectory-server ros-noetic-image-geometry ros-noetic-pcl-ros \
    # OpenCV dependencies
    python3-numpy \
    # Pangolin dependencies
    libgl1-mesa-dev \
    libglew-dev \
    libpython3-dev \
    libeigen3-dev \
    apt-transport-https \
    ca-certificates\
    software-properties-common \
    # Ceres dependencies
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    libsuitesparse-dev \
    # OpenCV dependencies
    libavcodec-dev libavformat-dev libswscale-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgtk-3-dev \
    # Kimera Dependencies
    libboost-all-dev libjpeg-dev libpng-dev libtiff-dev libvtk7-dev libgtk-3-dev gfortran \
    libparmetis-dev python3-wstool python3-catkin-tools libtbb-dev

# Build Pangolin
RUN cd /tmp && git clone https://github.com/stevenlovegrove/Pangolin && \
    cd Pangolin && git checkout v0.6 && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-std=c++11 .. && \
    make -j8 && make install && \
    cd / && rm -rf /tmp/Pangolin

ENV ROS_DISTRO noetic
ENV LANG en_US.UTF-8

# Setup catkin ws
RUN mkdir -p /catkin_ws/src /catkin_ws/build /catkin_ws/devel /catkin_ws/install

# TUI helpers and config files
COPY docker_build_utils/bashrc /root/.bashrc
COPY docker_build_utils/tmux.conf /root/.tmux.conf
COPY docker_build_utils/vimrc /root/.vimrc
COPY docker_build_utils/bash_profile_ext /tmp/bash_profile_ext
RUN cat /tmp/bash_profile_ext >> /root/.bash_profile && rm /tmp/bash_profile_ext

# Setup ros entrypoint and post create command that compiles everything
COPY docker_build_utils/ros_entrypoint.sh /ros_entrypoint.sh
COPY docker_build_utils/post_create_command_kimera.sh /post_create_command.sh
RUN chmod +x /ros_entrypoint.sh
RUN chmod +x /post_create_command.sh

USER $USERNAME
# terminal colors with xterm
ENV TERM xterm-256color
WORKDIR /
CMD ["bash"]
